name: line_notify
description: This is a Line Notify API wrapping library for the Dart language licensed under BSD 3-Clause.
version: 2.0.1
homepage: https://github.com/myConsciousness/line-notify.dart

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  http: ^0.13.4

dev_dependencies:
  test: ^1.16.8
